
epic_press: str = "/media/lmserhii/Storage/Works/01_EPICENTR/household/пресси"
epic_incubator: str = "/media/lmserhii/Storage/Works/01_EPICENTR/household/інкубатори"
epic_korm: str = "/media/lmserhii/Storage/Works/01_EPICENTR/household/кормоподрібнювачі"
epic_gaz: str = "/media/lmserhii/Storage/Works/01_EPICENTR/household/газові комплекти"
epic_house_tech: str = "/media/lmserhii/Storage/Works/01_EPICENTR/household/техніка для кухні"
epic_grand: str = "/media/lmserhii/Storage/Works/01_EPICENTR/tools"

roz_press: str = "/media/lmserhii/Storage/Works/03_Rozetka/Household/преса"
roz_gaz: str = "/media/lmserhii/Storage/Works/03_Rozetka/Household/туристичні плити"
roz_incubator: str = "/media/lmserhii/Storage/Works/03_Rozetka/Household/inkubatory"
roz_grand: str = "/media/lmserhii/Storage/Works/03_Rozetka/GRAND"
roz_sushka: str = "/media/lmserhii/Storage/Works/03_Rozetka/Household/Сушарки"

prom_press: str = "/media/lmserhii/Storage/Works/02_PROM/press.xlsx"
prom_korm: str = "/media/lmserhii/Storage/Works/02_PROM/kormorezky.xlsx"
prom_incubator: str = "/media/lmserhii/Storage/Works/02_PROM/incubatory.xlsx"
prom_gaz: str = "/media/lmserhii/Storage/Works/02_PROM/GAZ.xlsx"
prom_grand: str = "/media/lmserhii/Storage/Works/02_PROM/grand_eltos.xlsx"  
prom_kitchen: str = "/media/lmserhii/Storage/Works/02_PROM/kitchen.xlsx"
prom_mangal: str = "/media/lmserhii/Storage/Works/02_PROM/mangal.xlsx"
prom_mangalKomplekt: str = "/media/lmserhii/Storage/Works/02_PROM/mangal-komplekt.xlsx"
prom_mangalChehol: str = "/media/lmserhii/Storage/Works/02_PROM/mangal-chehol.xlsx"
