epic_press: str = r"D:\Works\01_EPICENTR\household\пресси"
epic_incubator: str = r"D:\Works\01_EPICENTR\household\інкубатори"
epic_korm: str = r"D:\Works\01_EPICENTR\household\кормоподрібнювачі"
epic_gaz: str = r"D:\Works\01_EPICENTR\household\газові комплекти"
epic_house_tech: str = r"D:\Works\01_EPICENTR\household\техніка для кухні"

roz_press: str = r"D:\Works\03_Rozetka\Household\преса"
roz_gaz: str = r"D:\Works\03_Rozetka\Household\туристичні плити"
roz_incubator: str = r"D:\Works\03_Rozetka\Household\inkubatory"
roz_grand: str = r"D:\Works\03_Rozetka\GRAND"
roz_sushka: str = r"D:\Works\03_Rozetka\Household\Сушарки"

prom_press: str = r"D:\Works\02_PROM\press.xlsx"
prom_korm: str = r"D:\Works\02_PROM\kormorezky.xlsx"
prom_incubator: str = r"D:\Works\02_PROM\incubatory.xlsx"
prom_gaz: str = r"D:\Works\02_PROM\GAZ.xlsx"
prom_grand: str = r"D:\Works\02_PROM\grand_eltos.xlsx"
prom_kitchen: str = r"D:\Works\02_PROM\kitchen.xlsx"
prom_mangal: str = r"D:\Works\02_PROM\mangal.xlsx"
prom_mangalKomplekt: str = r"D:\Works\02_PROM\mangal-komplekt.xlsx"
prom_mangalChehol: str = r"D:\Works\02_PROM\mangal-chehol.xlsx"
