epic_press = r"D:\Works\01_EPICENTR\household\пресси"
epic_incubator = r"D:\Works\01_EPICENTR\household\інкубатори"
epic_korm = r"D:\Works\01_EPICENTR\household\кормоподрібнювачі"
epic_gaz = r"D:\Works\01_EPICENTR\household\газові комплекти"
epic_house_tech = r"D:\Works\01_EPICENTR\household\техніка для кухні"
